version: '3'

services:
  jekyll:
    container_name: asbjornu.github.io
    image: jekyll/jekyll:3.8.5
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll